### ISSUE TITLE
Pre-Approval Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/pre-approval#1]

**Comment by crisner1978** [comment]
- [x]  Build Pre-approval form
- [x]  implement validation for all required fields
- [x]  implement error handling for form and fields
- [x]  connect to the F & I - Slack Channel
- [x]  build a Page that accepts a VIN
- [x]  populate vehicle data [https://listings.vin](https://listings.vin)
- [x]  get stock photo for that vehicle from [https://stock.photos.vin](https://stock.photo.vins)
- [x]  keep styling basic Tailwind

**Comment by crisner1978** [comment]
- https://pre-approval.driv.ly/
- with VIN https://pre-approval.driv.ly/1D7RV1CT8AS103067

- waiting on Route 1...

**Comment by crisner1978** [comment]
Added back button
- searchParams: cancelUrl
- vin example url = [https://pre-approval.driv.ly/1C4RJFBG2MC686287?cancelUrl=https%3A%2F%2Fcloud-motors-com.dev.driv.ly%2F19UDE2F7XNA000125](https://pre-approval.driv.ly/1C4RJFBG2MC686287?cancelUrl=https%3A%2F%2Fcloud-motors-com.dev.driv.ly%2F19UDE2F7XNA000125)
- home example url = [https://pre-approval.driv.ly/?cancelUrl=https://cloud-motors-com.dev.driv.ly/19UDE2F7XNA000125](https://pre-approval.driv.ly/?cancelUrl=https://cloud-motors-com.dev.driv.ly/19UDE2F7XNA000125)
